version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/tests"
    update_schedule: "live"
    default_reviewers:
    - tomas-stefano
    - brenetic
  - package_manager: "docker"
    directory: "/tests"
    update_schedule: "daily"
    default_reviewers:
    - tomas-stefano
    - brenetic
